bulls and cows
mate-academy/js_bulls-and-cows pull request #32
Opened 2019-11-22 19:22 UTC by olesmarola

2019-11-25 10:01 UTC, vpolets requested changes

2019-11-25 10:01 UTC, vpolets commented on src/bullsAndCows.js
> +  return farm;
давай не будемо писати полотна коду а ділити це на блоки? використовуй пусті строки для розділення блоків коду

2019-11-25 11:33 UTC, olesmarola commented on src/bullsAndCows.js
> +  return farm;
окей, а то у меня линтер сначала ругается, что пустые строки есть, но как тесты запустил, то перестает ругаться

2019-11-26 17:37 UTC, vpolets approved these changes

2024-05-29 16:49 UTC, closed without merging