Develop
mate-academy/js_bulls-and-cows pull request #68
Opened 2020-05-22 12:31 UTC by liliya-dev

2020-05-22 14:27 UTC, kvalenty requested changes

2020-05-22 14:27 UTC, kvalenty commented on src/bullsAndCows.js
> +  let cowsNum = 0;
можно перенести под все проверки, чтобы не оглашать лишний раз переменные

2020-05-22 17:10 UTC, kvalenty approved these changes

2020-05-25 16:33 UTC, danheim approved these changes

2020-05-25 16:33 UTC, danheim commented on src/bullsAndCows.js
> +    || !isRepeatNum(enteredNumber)) {
```suggestion
  if (
    enteredNumber === undefined
    || generatedNumber.length !== enteredNumber.length
    || !isRepeatNum(enteredNumber)
  ) {
```

2023-03-15 11:01 UTC, closed without merging