solution
mate-academy/js_bulls-and-cows pull request #72
Opened 2020-05-23 11:53 UTC by bran4u

2020-05-26 11:31 UTC, hryshko-denys approved these changes

2020-05-26 11:31 UTC, hryshko-denys commented on src/bullsAndCows.js
> +    return undefined;
можна просто return, без undefined

2020-05-26 11:31 UTC, hryshko-denys commented on src/bullsAndCows.js
> +  return result;
можеш просто об'єкт повертати, а то запутано виглядає

2020-05-27 12:57 UTC, danheim requested changes

2020-05-27 12:57 UTC, danheim commented on src/bullsAndCows.js
> +  return result;
объект result бесполезный, удали его и возвращай сразу { bulls, cows }

2020-05-28 08:25 UTC, danheim approved these changes

2020-05-28 08:25 UTC, danheim commented on src/bullsAndCows.js
> +      if (generatedNumber.includes(enteredNumber[i])) {
else if

2024-05-24 15:55 UTC, closed without merging